# Generated by Django 5.2.6 on 2025-09-19 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('skills', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=30)),
                ('customer_email', models.EmailField(max_length=254)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.staff')),
            ],
            options={
                'indexes': [models.Index(fields=['staff', 'start'], name='booking_boo_staff_i_b518b3_idx'), models.Index(fields=['staff', 'end'], name='booking_boo_staff_i_198e7e_idx')],
            },
        ),
    ]
